In [1]:
# This code was written from the Computerphile video on YouTube

# Python Sudoku Solver using Backtracking Algorithm

# Video Title - Python Sudoku Solver - Computerphile

# Video Link - <https://www.youtube.com/watch?v=G_UYXzGuqvM>

# Channel Name - Computerphile

# Channel Link - <https://www.youtube.com/user/Computerphile>

# Credits - Computerphile team and Professor Thorsten Altenkirch

In [2]:
# importing the required libraries
import numpy as np


In [22]:
# defining the board
grid = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9],
]

# numpy array of the board as np array operation is faster than list and pretty to print
grid_arr = np.array(grid) 
grid_arr

array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
       [6, 0, 0, 1, 9, 5, 0, 0, 0],
       [0, 9, 8, 0, 0, 0, 0, 6, 0],
       [8, 0, 0, 0, 6, 0, 0, 0, 3],
       [4, 0, 0, 8, 0, 3, 0, 0, 1],
       [7, 0, 0, 0, 2, 0, 0, 0, 6],
       [0, 6, 0, 0, 0, 0, 2, 8, 0],
       [0, 0, 0, 4, 1, 9, 0, 0, 5],
       [0, 0, 0, 0, 8, 0, 0, 7, 9]])

In [23]:
# defining the function to check whether a selected row, column, and number is valid or not
def possible(y, x, n):
    global grid # using the global variable
    for i in range(9):
        if grid[y][i] == n: # checking whether the number is already present in the row
            return False
    for i in range(9):
        if grid[i][x] == n: # checking whether the number is already present in the column
            return False
    
    x0 = (x//3)*3 # finding the starting x point of the 3x3 block
    y0 = (y//3)*3 # finding the starting y point of the 3x3 block
    for i in range(3):
        for j in range(3):
            if grid[y0+i][x0+j] == n: # checking whether the number is already present in the 3x3 block
                return False
    return True

In [24]:
# checking the function
possible(4, 4, 3) # from the output we can see that the number 3 is present in the row, column, or in 3x3 block

False

In [25]:
possible(4, 4, 5) # from the output we can see that the number 5 is present in the row, column, or in 3x3 block

True

In [28]:
def solve():
    global grid # using the global variable
    
    # checking for the empty space in the board
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0: # checking for an empty cell
                for n in range(1, 10):
                    if possible(y, x, n):
                        grid[y][x] = n # assigning the number to the empty cell
                        solve()
                        grid[y][x] = 0 # backtracking
                return
    print(np.array(grid)) # printing the board
    
    input("More?") # asking the user whether he/she wants to see more solutions or not

In [29]:
solve()
print(grid_arr)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]
